[build]
  publish = "."

[[redirects]]
  from = "/partners"
  to = "/partners/"
  status = 301

[[redirects]]
  from = "/home"
  to = "/home/"
  status = 301

[[redirects]]
  from = "/care"
  to = "/care/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
